# Example dek configuration

[package.pacman]
items = ["git", "tree", "fzf", "bat", "btop"]

[package.cargo]
items = ["bat", "eza"]

[package.go]
items = [
  "github.com/junegunn/fzf@latest",
  "github.com/zcag/cacheup@latest",
  "github.com/zcag/ccsv@latest",
  "github.com/zcag/tali@latest",
  "github.com/zcag/goscript@latest",
  "github.com/antonmedv/fx@latest"
]

# Services - systemd
[[service]]
name = "xremap"
state = "active"
enabled = true

[[service]]
name = "nginx"
state = "active"

# Shell
[alias]
la = "ls -larth"
v = "nvim"
lg = "lazygit"
ccsvp = "ccsv --sep '|'"
lens =  "csvlens"
lensp = "csvlens --delimiter '|'"

[env]
EDITOR = "nvim"

# System
timezone = "Europe/Istanbul"
